version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: pubapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pub-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: pubwebserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - pub-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: pubdb
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: publications
      MYSQL_ROOT_PASSWORD: N1mx@9653
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - pubdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - pub-network

# Docker Networks
networks:
  pub-network:
    driver: bridge

# Volumes
volumes:
  pubdata:
    driver: local
